---
- name: download_data_playbook
  hosts: localhost
  connection: local
  tasks: 
  - name: Create data directory
    ansible.builtin.file:
      path: /data
      state: directory
      mode: '0775'
  
  - name: Create downloader directory 
    ansible.builtin.file:
      path: /downloader
      state: directory
      mode: '0775'
    
  - name: Clone downloader repository
    git:
      repo: https://github.com/AkumuYuma/eodag-data-downloader.git
      dest: /downloader
      clone: yes
      update: yes
  
  # - name: Install requirements for data download
  #   ansible.builtin.pip:
  #     requirements: /downloader/requirements.txt
      # virtualenv: /downloader/venv
      # virtualenv_python: python3.10.9
  - name: Install requirements for data download
    ansible.builtin.pip:
      name: eodag 

  - name: Install requirements for data download
    ansible.builtin.pip:
      name: ruamel.yaml 

  - name: Printing variable valus
    ansible.builtin.debug:
      msg: 
      - "Variabile: '{{ downloading_input[0] }}'"
  
  # - name: Download data
  #   ansible.builtin.script: /downloader/downloader.py "{{ downloading_input[0] }}"
  #   args:
  #     executable: python3